name: Static Code Analysis

on: [pull_request]

jobs:
  phpcs:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # PHPUnit Bridge won't install a version of PHPUnit by default, but this will trick
      # it into doing so.
      - name: Install PHPUnit
        run: composer test -- --version

      - name: Run PHPStan
        run: composer test:analysis
