name: Unit Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['5.6', '7.0', 7.1', '7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        if: ${{ matrix.php != '7.4' }}
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Setup PHP w/ Code Coverage
        uses: shivammathur/setup-php@v2
        if: ${{ matrix.php == '7.4' }}
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest --no-progress

      - name: Run test suite
        if: ${{ matrix.php != '7.4' }}
        run: composer test

      - name: Run test suite with code coverage
        if: ${{ matrix.php == '7.4' }}
        run: composer test --coverage-text
